# Generated by Django 3.2 on 2021-05-09 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='相册创建时间'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='文件上传时间'),
        ),
        migrations.AlterField(
            model_name='label',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='标签创建时间'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='图片上传时间'),
        ),
        migrations.AlterField(
            model_name='section',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='thinking',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='账户创建时间'),
        ),
    ]
